encurtador/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    url(r'^$', 'encurtador_app.views.index'),
    url(r'encurtar', 'encurtador_app.views.encurtar'),


    url(r'^admin/', include(admin.site.urls)),
    url(r'^(?P<link>\w+)$', 'encurtador_app.views.linkar'),
)

encurtador_app/models.py
from django.db import models

class Url(models.Model):
    url = models.URLField()
    count = models.IntegerField(blank=True,null=True,default=0)

encurtador_app/forms.py
# -*- coding: utf8 -*-
from django import forms

class UrlForm(forms.Form):
    url = forms.URLField(widget=forms.TextInput(attrs= {'class':'form-control', 'required': 'true','placeholder': u'URL'}))

encurtador_app/views.py
# -*- coding: utf8 -*-
from django.shortcuts import render,render_to_response,get_object_or_404
from django.template import RequestContext
from django.http import HttpResponsePermanentRedirect

from encurtador_app.forms import *
from encurtador_app.models import *
from encurtador_app.util import *

def index(request):
    """ View para página inicial """

    form_url = UrlForm()

    return render_to_response('index.html', {'form_url':form_url}, RequestContext(request))

def encurtar(request):
    " Grava a URL inserida pelo usuário retornando a url encurtada"
    form_url = UrlForm()
    url_curta = ''

    if request.method == 'POST':
        form_url = UrlForm(request.POST)
        if form_url.is_valid():
            url_field = form_url.cleaned_data['url']

            try:
                url = Url.objects.get(url=url_field)
            except Url.DoesNotExist:
                url = Url(url=url_field)
                url.save()
            "encurta a url com base no ID do objeto gravado"
            url_curta = base62.from_decimal(url.id)

    return render_to_response('index.html', {'form_url':form_url,'url_curta':url_curta}, RequestContext(request))

def linkar(request, link):
    " Busca se a url já foi inserida"
    url = get_object_or_404(Url, id=base62.to_decimal(link))
    url.count += 1
    url.save()
    return HttpResponsePermanentRedirect(url.url)

templates/includes/base.html
<!DOCTYPE html>
<html>

<head>
    <title>{% block titulo %}{% endblock %}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    {% load static %}

    <link href="{% static "css/plugins/bootstrap/bootstrap.min.css" %}" rel="stylesheet" type="text/css" />
    <link href="{% static "css/plugins/bootstrap/bootstrap-theme.min.css" %}" rel="stylesheet" type="text/css" />
    {% block css %}{% endblock %}

    <script type="text/javascript" src="{% static "js/plugins/jquery-1.11.0.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/plugins/bootstrap.min.js" %}"></script>
    {% block js %}{% endblock %}

</head>

<body>
    {% block conteudo %}{% endblock %}
</body>

</html>

templates/index.html
{% extends 'includes/base.html' %}
{% block titulo %}Encutador de Urls{% endblock %}
{% block css %}
    {% load static %}
{% endblock %}
{% block js %}
    {% load static %}
{% endblock %}


{% block conteudo %}
    <div class="container">
        <div class="page-header">
            <h1> Bem Vindo ao Encurtador de URL's</h1>
        </div>

        <div class="panel">
            <form action="/encurtar/" method="post" role="form">{% csrf_token %}
                <div class="row">
                    <div class="form-group col-sm-8 col-md-10 col-sm-11">
                        <label for="id_url">Insira a URL a ser encutada</label>
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-sm-8 col-md-10 col-sm-11">
                        {{ form_url.url }}
                    </div>
                    <button type="submit" class="btn btn-primary col-sm-4 col-sm-2 col-lg-1">Encurtar</button>
                </div>
            </form>
        </div>
        <div class="panel">
            {% if url_curta%}
                <p>Url encurtada : </p>
                <a href="/{{ url_curta }}">/{{ url_curta }}</a>
            {% endif %}
        </div>

    </div>

{% endblock %}